<?php
define('PREVNEXT_TITLE_FIRST_PAGE', 'first page');
define('PREVNEXT_TITLE_LAST_PAGE', 'last page');
define('PAGINATION_TITLE_OVERVIEW', 'overview');
define('NAV_BRAND', 'Our offers');
define('TEXT_RATING_KUNDEN', 'Product Reviews');  
define('TEXT_EIN_RATING_KUNDEN', 'Product Review');
define('SELECT_VIEW', 'Select a view: ');
define('KOSTEN_INFO', '* All prices incl. VAT plus shipping rates and possibly shipping fees unless otherwise stated');
define('KOSTEN_INFO_HAENDLER', '* All prices excl. VAT plus shipping rates and possibly shipping fees unless otherwise stated');
define('IMAGE_BUTTON_PREVIEW', 'Preview');
define('IMAGE_BUTTON_PRODUCT_MORE', 'Details');
define('APS_TEXT_STANDARD', 'Products per page');
define('SORTING_STANDARD', 'Sort by ...');
define('SORTING_ABC_ASC', 'A to Z');
define('SORTING_ABC_DESC', 'Z to A');
define('SORTING_PRICE_ASC', 'Price descend');
define('SORTING_PRICE_DESC', 'price ascend');
define('HEADING_CONTENT', 'Information');
define('SERVICE_BOX_LINK_NAME', 'Service');
define('SITEMAP_TITLE', 'Sitemap');
// Bestellungsmail und -druck
define('ORDER_THANK_YOU_TOP', 'Thank you for your order. Your order information is available below.');
define('ORDER_HEAD', 'Order');
define('ORDER_ORDER_HEAD', 'Data');
define('ORDER_INFO_HEAD', 'Customer information');
define('ORDER_ARTIKEL_HEAD', 'Ordered items');
define('ORDER_COMMENTS_HEAD', 'Comments:');
define('ORDER_PAYMENTS_HEAD', 'Paymentinformation:');
define('ORDER_DUTY_INFO_HEAD', 'Dutyinformation:');
define('ORDER_THANK_YOU_BOTTOM', 'Thank you for your trust, we hope to welcome you back to our shop.');
define('TEXT_PRINT', 'Print');
define('IMAGE_BUTTON_CONTINUE_SHOPPING', 'Continue Shopping');